version: "3.9"

services:
  qrcode:
    build:
      context: .
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    image: qrcode:1.0
    container_name: qrcode
    restart: "unless-stopped"
    networks:
      - qrcode_network
    ports:
      - "8080:80"
    user: "${PUID}:${PGID}"
    #environment:
      #ADMIN_USER: "superadmin" # not supported yet please see road map
      #ADMIN_PASSWORD: "superadmin" # not supported yet please see road map
      #DATABASE_HOST: "mariadb" # not supported yet please see road map
      #DATABASE_NAME: "qrcode" # not supported yet please see road map
      #DATABASE_USER: "qrcode" # not supported yet please see road map
      #DATABASE_PASSWORD: "changeme" # not supported yet please see road map
    volumes:
      - ./data/app/config:/var/www/html/config
      - ./data/app/saved_qrcode:/var/www/html/saved_qrcode

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: "unless-stopped"
    environment:
      MARIADB_ROOT_PASSWORD: "changeme"
      MARIADB_DATABASE: "qrcode"
      MARIADB_USER: "qrcode"
      MARIADB_PASSWORD: "changeme"
    networks:
      - qrcode_network
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  qrcode_network:
    driver: bridge
    name: qrcode
